on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            target: wasm32-unknown-unknown
      - run: cargo install --locked trunk
      - run: cargo update
      - run: trunk build --dist ./
      - run: touch .nojekyll
      - run: echo "justanotherbyte.me" > CNAME
      - run: echo '<!DOCTYPE html><html lang="en"><head> <meta charset="UTF-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <script type="text/javascript" src="/assets/ghspa.js"></script> <title>404</title></head><body> </body></html>' > "404.html"
      - name: deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# thank you to Zomatree (https://github.com/Zomatree) for this